# All config option can be found here:
# https://starship.rs/config/#prompt

# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
# It's disabled because in Warp this happens by default and
# this causes an empty space before the prompt text
add_newline = false

# Symbols that appear before your command input
# It's disabled because Warp puts the input in a separeted line
[character]
# success_symbol = '[👉](bold)'
# error_symbol = '[🔥](bold)'
disabled = true

# Disabling package module
[package]
disabled = true
